"""library_build.py — WuaDVI-lib build hook (declared by library.json).

Generates the RP2354B firmware payload header and puts it on the LIBRARY's
include path, so a consuming application never has to know the RP exists: it
depends on WuaDVI-lib and the RP image comes with it, pinned and verified.

── Two PlatformIO details this depends on ─────────────────────────────────────
1. A library extraScript runs via SCons `SConscript(..., exports={...})`, which
   `exec`s the file WITHOUT defining `__file__`.  Deriving the library root from
   `__file__` therefore raises NameError.  PlatformIO exports `pio_lib_builder`
   for exactly this: `pio_lib_builder.path` is the library root, wherever the
   library was installed from (registry, git URL or local path).
2. The generated header is added to CPPPATH of the LIBRARY's env only, and is
   included solely by the library's .cpp files — never by the public header.
   The real payload is a ~104 KB C array; putting it in a public header would
   compile it into every translation unit that includes WuaDVI.h.

The full embedder (release download, SHA-256 verification, UF2 → flat image,
C array emission) is the existing tools/embed_rp_firmware.py from
WuaDVI-firmware, ported here in phase 1.  This generates the version metadata
only, which is enough to prove the mechanism.
"""
import os

Import("env", "pio_lib_builder")  # noqa: F821  (injected by SCons/PlatformIO)

# The library root, from PlatformIO's own library builder (see note 1 above).
LIB_DIR = pio_lib_builder.path     # noqa: F821
ASSETS_DIR = os.path.join(LIB_DIR, "assets", "rp-firmware")


def _die(msg):
    raise SystemExit(f"[WuaDVI-lib] error: {msg}")


def _read_pinned_version():
    version_file = os.path.join(ASSETS_DIR, "VERSION")
    if not os.path.isfile(version_file):
        _die(f"missing {version_file} (it pins which RP release to use)")
    return open(version_file).read().strip()


def _generate(version):
    out_dir = os.path.join(env.subst("$BUILD_DIR"), "wuadvi_generated")  # noqa: F821
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "wuadvi_rp_payload.h")

    header = "\n".join([
        "/* wuadvi_rp_payload.h - GENERATED by WuaDVI-lib - DO NOT EDIT.",
        " * Library-internal: included by the library's sources only. */",
        "#pragma once",
        "",
        f'#define WUADVI_RP_PAYLOAD_VERSION "{version}"',
        "#define WUADVI_RP_PAYLOAD_PRESENT  1",
        "",
    ])

    if not (os.path.isfile(out_path) and open(out_path, newline="").read() == header):
        with open(out_path, "w", newline="\n") as f:
            f.write(header)

    env.Append(CPPPATH=[out_dir])  # noqa: F821  (library env — see note 2)

    print(f"[WuaDVI-lib] library root : {LIB_DIR}")
    print(f"[WuaDVI-lib] RP payload   : v{version}")
    print(f"[WuaDVI-lib] generated    : {out_path}")


_generate(_read_pinned_version())
