/**
 * @file WuaDVI.cpp
 * @brief The WuaDVI board — see WuaDVI.h.
 */
#include "WuaDVI.h"

#include <Preferences.h>

#include "display_link.h"
#include "lvgl_port.h"
#include "rp_boot.h"
#include "rp_manager.h"
#include "spi_bus.h"

/* Library-internal, generated by scripts/library_build.py (declared as this
 * library's extraScript in library.json).  Never include this from a public
 * header: it carries the display-engine image as a ~100 KB C array. */
#include "wuadvi_rp_payload.h"

#ifndef WUADVI_RP_PAYLOAD_PRESENT
#error "WuaDVI-lib: the library build hook did not generate the RP payload header"
#endif

/**
 * @brief How long without display-engine telemetry counts as "it has reset".
 *
 * The RP piggybacks telemetry on every pixel packet while it is displaying.
 * If that stops, it has reset — for instance an overclock glitch in the
 * 800x600 mode watchdog-rebooted it back to its splash — and we would
 * otherwise stream forever to a device that is no longer listening.
 */
#define WUADVI_RP_DEAD_MS 6000u

/** Pause before retrying a failed bring-up, so a hard fault does not spin. */
#define WUADVI_RETRY_MS 3000u

bool WuaDVI::startPipeline(void) {
    rp_manager_status_t st;
    if (!rp_manager_bring_up(&st)) {
        m_error = "display engine did not come up";
        return false;
    }

    /* LVGL is started once and kept across recoveries: the application's
     * objects live in it, and rebuilding would destroy the interface the user
     * created after begin(). */
    if (!m_lvgl_started) {
        if (!lvgl_port_init()) {
            m_error = "LVGL initialization failed";
            return false;
        }
        m_lvgl_started = true;
    }

    /* Force a full repaint so the display engine leaves its splash at once —
     * on first start and on every recovery. */
    lv_obj_invalidate(lv_screen_active());

    m_error = "";
    return true;
}

/* Where setResolution() stores its choice.  NVS, not RTC memory: the mode must
 * survive a power cycle, not only a reset. */
#define WUADVI_NVS_NAMESPACE "wuadvi"
#define WUADVI_NVS_KEY_RES   "res"

bool WuaDVI::storedResolution(wua_resolution_id_t *out_res) {
    Preferences prefs;
    if (!prefs.begin(WUADVI_NVS_NAMESPACE, true /* read-only */))
        return false;
    const uint8_t id = prefs.getUChar(WUADVI_NVS_KEY_RES, 0);
    prefs.end();
    if (id == 0 || wua_resolution_by_id(id) == nullptr)
        return false;
    if (out_res != nullptr)
        *out_res = (wua_resolution_id_t)id;
    return true;
}

void WuaDVI::clearStoredResolution(void) {
    Preferences prefs;
    if (!prefs.begin(WUADVI_NVS_NAMESPACE, false))
        return;
    prefs.remove(WUADVI_NVS_KEY_RES);
    prefs.end();
}

bool WuaDVI::setResolution(wua_resolution_id_t res) {
    if (wua_resolution_by_id((uint8_t)res) == nullptr) {
        m_error = "unknown display mode";
        return false;
    }

    Preferences prefs;
    if (!prefs.begin(WUADVI_NVS_NAMESPACE, false)) {
        m_error = "cannot open storage to save the display mode";
        return false;
    }
    prefs.putUChar(WUADVI_NVS_KEY_RES, (uint8_t)res);
    prefs.end();

    delay(50); /* let any pending serial output reach the host */
    ESP.restart();
    return true; /* not reached */
}

bool WuaDVI::begin(wua_resolution_id_t res) {
    /* A mode stored by setResolution() wins over the argument: that is what
     * makes the change persist across the restart it performs. */
    wua_resolution_id_t stored;
    if (storedResolution(&stored)) {
        if (stored != res) {
            /* Say so.  Silently ignoring an explicit argument is how a sketch
             * that asks for 800x600 comes up at 640x480 with no explanation —
             * and how every demo in a catalogue looks identical. */
            const wua_resolution_t *s_r = wua_resolution_by_id((uint8_t)stored);
            const wua_resolution_t *a_r = wua_resolution_by_id((uint8_t)res);
            Serial.printf("[WuaDVI] using the stored mode %s instead of %s "
                          "(press 'c' on the console to forget it)\n",
                          s_r ? s_r->name : "?", a_r ? a_r->name : "?");
        }
        res = stored;
    }

    if (!wua_resolution_set_active((uint8_t)res)) {
        m_error = "unknown display mode";
        return false;
    }

    /* Strap and UART pins to high impedance before anything else: they share
     * the display engine's internal-flash QSPI bus, and driving them while it
     * boots would keep it out of its normal firmware. */
    rp_boot_release_pins();
    spi_bus_init();

    m_running = startPipeline();
    return m_running;
}

void WuaDVI::loop(void) {
    if (!m_running) {
        delay(WUADVI_RETRY_MS);
        m_running = startPipeline();
        return;
    }

    delay(lvgl_port_loop());

    if (display_link_telemetry_age() > WUADVI_RP_DEAD_MS) {
        /* The display engine reset under us. Re-run the bring-up to reset it
         * and re-arm the stream; the interface is preserved and repainted. */
        m_running = startPipeline();
    }
}

bool WuaDVI::temperature(int16_t *out_c10) const {
    if (out_c10 == nullptr)
        return false;
    uint32_t age_ms = 0;
    if (!display_link_get_rp_temp(out_c10, &age_ms))
        return false;
    return age_ms < WUADVI_RP_DEAD_MS;
}

uint32_t WuaDVI::rectsSent(void) const {
    return lvgl_port_rects_sent();
}

uint32_t WuaDVI::rectsFailed(void) const {
    return lvgl_port_rects_failed();
}

const char *WuaDVI::displayEngineVersion(void) {
    return RP_PAYLOAD_VERSION_STRING;
}

void WuaDVI::printConsoleHelp(void) {
    Serial.println();
    Serial.println("  ── WuaDVI display mode ─────────────────────────");
    Serial.println("   1  320x240 RGB565      4  800x600 mono");
    Serial.println("   2  400x240 RGB565      5  1280x720 mono (30 Hz)");
    Serial.println("   3  640x480 mono");
    Serial.println("   c  forget the stored mode   i  status   ?  this list");
    Serial.println("  Switching stores the mode and restarts the board.");
}

bool WuaDVI::consoleKey(char key) {
    switch (key) {
    case '1': setResolution(WUA_RES_320x240); return true; /* restarts */
    case '2': setResolution(WUA_RES_400x240); return true;
    case '3': setResolution(WUA_RES_640x480x1); return true;
    case '4': setResolution(WUA_RES_800x600x1); return true;
    case '5': setResolution(WUA_RES_1280x720x1); return true;

    case 'c':
    case 'C':
        clearStoredResolution();
        Serial.println("\n  stored mode forgotten - restart to use the mode "
                       "this sketch asks for");
        return true;

    case 'i':
    case 'I': {
        int16_t t;
        wua_resolution_id_t stored;
        Serial.printf("\n  mode     : %s (%ux%u)\n", resolutionName(), width(),
                      height());
        Serial.printf("  stored   : %s\n",
                      storedResolution(&stored)
                          ? wua_resolution_by_id((uint8_t)stored)->name
                          : "(none - this sketch's choice is used)");
        Serial.printf("  engine   : v%s", displayEngineVersion());
        if (temperature(&t))
            Serial.printf(", %d.%d C", t / 10, abs(t % 10));
        Serial.println();
        Serial.printf("  packets  : %lu sent, %lu failed\n",
                      (unsigned long)rectsSent(), (unsigned long)rectsFailed());
        Serial.printf("  heap     : %u B\n", ESP.getFreeHeap());
        return true;
    }

    case '?':
    case 'h':
    case 'H': printConsoleHelp(); return true;

    default: return false; /* not ours - the sketch may want it */
    }
}
