/**
 * @file WuaDVI.cpp
 * @brief The WuaDVI board — see WuaDVI.h.
 */
#include "WuaDVI.h"

#include "display_link.h"
#include "lvgl_port.h"
#include "rp_boot.h"
#include "rp_manager.h"
#include "spi_bus.h"

/* Library-internal, generated by scripts/library_build.py (declared as this
 * library's extraScript in library.json).  Never include this from a public
 * header: it carries the display-engine image as a ~100 KB C array. */
#include "wuadvi_rp_payload.h"

#ifndef WUADVI_RP_PAYLOAD_PRESENT
#error "WuaDVI-lib: the library build hook did not generate the RP payload header"
#endif

/**
 * @brief How long without display-engine telemetry counts as "it has reset".
 *
 * The RP piggybacks telemetry on every pixel packet while it is displaying.
 * If that stops, it has reset — for instance an overclock glitch in the
 * 800x600 mode watchdog-rebooted it back to its splash — and we would
 * otherwise stream forever to a device that is no longer listening.
 */
#define WUADVI_RP_DEAD_MS 6000u

/** Pause before retrying a failed bring-up, so a hard fault does not spin. */
#define WUADVI_RETRY_MS 3000u

bool WuaDVI::startPipeline(void) {
    rp_manager_status_t st;
    if (!rp_manager_bring_up(&st)) {
        m_error = "display engine did not come up";
        return false;
    }

    /* LVGL is started once and kept across recoveries: the application's
     * objects live in it, and rebuilding would destroy the interface the user
     * created after begin(). */
    if (!m_lvgl_started) {
        if (!lvgl_port_init()) {
            m_error = "LVGL initialization failed";
            return false;
        }
        m_lvgl_started = true;
    }

    /* Force a full repaint so the display engine leaves its splash at once —
     * on first start and on every recovery. */
    lv_obj_invalidate(lv_screen_active());

    m_error = "";
    return true;
}

bool WuaDVI::begin(void) {
    /* Strap and UART pins to high impedance before anything else: they share
     * the display engine's internal-flash QSPI bus, and driving them while it
     * boots would keep it out of its normal firmware. */
    rp_boot_release_pins();
    spi_bus_init();

    m_running = startPipeline();
    return m_running;
}

void WuaDVI::loop(void) {
    if (!m_running) {
        delay(WUADVI_RETRY_MS);
        m_running = startPipeline();
        return;
    }

    delay(lvgl_port_loop());

    if (display_link_telemetry_age() > WUADVI_RP_DEAD_MS) {
        /* The display engine reset under us. Re-run the bring-up to reset it
         * and re-arm the stream; the interface is preserved and repainted. */
        m_running = startPipeline();
    }
}

bool WuaDVI::temperature(int16_t *out_c10) const {
    if (out_c10 == nullptr)
        return false;
    uint32_t age_ms = 0;
    if (!display_link_get_rp_temp(out_c10, &age_ms))
        return false;
    return age_ms < WUADVI_RP_DEAD_MS;
}

uint32_t WuaDVI::rectsSent(void) const {
    return lvgl_port_rects_sent();
}

uint32_t WuaDVI::rectsFailed(void) const {
    return lvgl_port_rects_failed();
}

const char *WuaDVI::displayEngineVersion(void) {
    return RP_PAYLOAD_VERSION_STRING;
}
