/**
 * @file WuaDVI.cpp
 * @brief The WuaDVI board — see WuaDVI.h.
 */
#include "WuaDVI.h"

#include <Preferences.h>

#include "display_link.h"
#include "lvgl_port.h"
#include "rp_boot.h"
#include "rp_manager.h"
#include "spi_bus.h"

/* Library-internal, generated by scripts/library_build.py (declared as this
 * library's extraScript in library.json).  Never include this from a public
 * header: it carries the display-engine image as a ~100 KB C array. */
#include "wuadvi_rp_payload.h"

#ifndef WUADVI_RP_PAYLOAD_PRESENT
#error "WuaDVI-lib: the library build hook did not generate the RP payload header"
#endif

/**
 * @brief How long without display-engine telemetry counts as "it has reset".
 *
 * The RP piggybacks telemetry on every pixel packet while it is displaying.
 * If that stops, it has reset — for instance an overclock glitch in the
 * 800x600 mode watchdog-rebooted it back to its splash — and we would
 * otherwise stream forever to a device that is no longer listening.
 */
#define WUADVI_RP_DEAD_MS 6000u

/** Pause before retrying a failed bring-up, so a hard fault does not spin. */
#define WUADVI_RETRY_MS 3000u

bool WuaDVI::startPipeline(void) {
    rp_manager_status_t st;
    if (!rp_manager_bring_up(&st)) {
        m_error = "display engine did not come up";
        return false;
    }

    /* LVGL is started once and kept across recoveries: the application's
     * objects live in it, and rebuilding would destroy the interface the user
     * created after begin(). */
    if (!m_lvgl_started) {
        if (!lvgl_port_init()) {
            m_error = "LVGL initialization failed";
            return false;
        }
        m_lvgl_started = true;
    }

    /* Force a full repaint so the display engine leaves its splash at once —
     * on first start and on every recovery. */
    lv_obj_invalidate(lv_screen_active());

    /* Start the activity clock here: a bring-up always repaints, so this is
     * the one moment we know packets are about to flow. */
    m_last_rects = lvgl_port_rects_sent();
    m_last_sent_ms = millis();

    m_error = "";
    return true;
}

/* Where a mode change made from a RUNNING sketch is left for the restart it
 * performs.  Only that case uses this — a setResolution() in setup() selects
 * the mode directly and never touches NVS.
 *
 * A ONE-SHOT: begin() consumes it and clears it.  A latch that outlived its
 * restart would override the sketch's own setup() forever, which is not
 * hypothetical — it is how a catalogue of demos each selecting a different
 * mode all came up in the same one.
 *
 * NVS rather than RTC memory because the reset path must survive a brownout
 * mid-restart, not only a clean reboot. */
#define WUADVI_NVS_NAMESPACE   "wuadvi"
#define WUADVI_NVS_KEY_PENDING "pending"

/** Read and clear the pending switch. @return false when none is waiting. */
static bool take_pending_resolution(wua_resolution_id_t *out_res) {
    Preferences prefs;
    if (!prefs.begin(WUADVI_NVS_NAMESPACE, false))
        return false;
    const uint8_t id = prefs.getUChar(WUADVI_NVS_KEY_PENDING, 0);
    if (id != 0)
        prefs.remove(WUADVI_NVS_KEY_PENDING);
    prefs.end();

    if (id == 0 || wua_resolution_by_id(id) == nullptr)
        return false;
    if (out_res != nullptr)
        *out_res = (wua_resolution_id_t)id;
    return true;
}

bool WuaDVI::setResolution(wua_resolution_id_t res) {
    if (wua_resolution_by_id((uint8_t)res) == nullptr) {
        m_error = "unknown display mode";
        return false;
    }

    /* Before begin(): nothing is displaying, so selecting the mode is all
     * there is to do.  This is the setup() case, and the common one. */
    if (!m_lvgl_started) {
        wua_resolution_set_active((uint8_t)res);
        m_error = "";
        return true;
    }

    /* After begin(): the mode is already live and cannot be changed under a
     * running scanout, so hand it to the restart. */
    Preferences prefs;
    if (!prefs.begin(WUADVI_NVS_NAMESPACE, false)) {
        m_error = "cannot open storage to request the display mode";
        return false;
    }
    prefs.putUChar(WUADVI_NVS_KEY_PENDING, (uint8_t)res);
    prefs.end();

    delay(50); /* let any pending serial output reach the host */
    ESP.restart();
    return true; /* not reached */
}

bool WuaDVI::begin(void) {
    /* Never wait for a serial host.  Bring-up prints a few dozen lines, and a
     * USB-CDC port that is plugged in but has no reader counts as connected —
     * the TX buffer fills, the write blocks, and the board sits on the display
     * engine's splash until somebody opens a monitor.  Useless in the field.
     *
     * The value must be small but NOT zero.  HWCDC::write() gives up after
     * `tries = tx_timeout_ms` milliseconds without progress, decrementing
     * `tries` each time — so zero underflows a uint32_t on the first pass and
     * the loop waits about 49 days instead of not waiting at all.  Ten
     * milliseconds is enough for a real terminal to keep up and short enough
     * that an absent one costs nothing worth measuring. */
#if defined(ARDUINO_USB_CDC_ON_BOOT) && ARDUINO_USB_CDC_ON_BOOT
    Serial.setTxTimeoutMs(10);
#endif

    /* Normally the mode is whatever setResolution() selected in setup() — or
     * the table default if it was never called.  The exception is a change
     * requested from a running sketch: that restart brought us back through
     * setup(), whose setResolution() call has just re-selected the OLD mode,
     * so the request has to win here.  It is consumed in the same breath, so
     * it wins exactly once and a power cycle follows setup() again. */
    wua_resolution_id_t pending;
    const uint8_t id = take_pending_resolution(&pending) ? (uint8_t)pending
                                                         : wua_resolution()->id;

    if (!wua_resolution_set_active(id)) {
        m_error = "unknown display mode";
        return false;
    }

    /* Strap and UART pins to high impedance before anything else: they share
     * the display engine's internal-flash QSPI bus, and driving them while it
     * boots would keep it out of its normal firmware. */
    rp_boot_release_pins();
    spi_bus_init();

    m_running = startPipeline();
    return m_running;
}

void WuaDVI::loop(void) {
    if (!m_running) {
        delay(WUADVI_RETRY_MS);
        m_running = startPipeline();
        return;
    }

    delay(lvgl_port_loop());

    /* The display engine reports its health on the back of the pixel packets,
     * so telemetry only flows while there is something to draw.  A screen that
     * has settled — a status board with no clock on it, which is an ordinary
     * thing to build — sends nothing, hears nothing back, and used to be
     * declared dead every six seconds: the pipeline was rebuilt, the rebuild
     * forced a repaint, telemetry returned, and six seconds later it happened
     * again.  A healthy board looked like one stuck in a boot loop.
     *
     * Silence is therefore only evidence of death when we were speaking. If
     * nothing has been sent, nothing can have come back, and the right answer
     * is to wait rather than to reset the display engine under a working
     * screen. A genuinely dead engine behind a static screen goes unnoticed
     * until the next redraw, which is when it starts to matter. */
    const uint32_t sent = lvgl_port_rects_sent();
    if (sent != m_last_rects) {
        m_last_rects = sent;
        m_last_sent_ms = millis();
    }

    /* The question is not "how old is the telemetry" but "how long have we been
     * sending without hearing back".  Telemetry is always at least as old as
     * the last packet, so comparing both against the same window makes them
     * cross it together — a static screen then trips the check with about a
     * hundred milliseconds to spare, which is what a healthy board caught in a
     * six-second rebuild cycle looked like.
     *
     * The gap between the two is the real signal: small means the last packet
     * was answered, large means packets are going out and nothing is coming
     * back. */
    const uint32_t tele_age = display_link_telemetry_age();
    const uint32_t send_age = millis() - m_last_sent_ms;
    const uint32_t unanswered = (tele_age > send_age) ? (tele_age - send_age) : 0;

    if (unanswered > WUADVI_RP_DEAD_MS) {
        /* Say WHY before acting.  A recovery that prints only its bring-up
         * looks identical to a boot loop, and the two have opposite causes:
         * one is the display engine dying, the other is this side deciding it
         * did.  These three numbers separate them. */
        Serial.printf("[RP] recovering: telemetry %lu ms old, %lu rects sent, "
                      "last send %lu ms ago\n",
                      (unsigned long)tele_age, (unsigned long)sent,
                      (unsigned long)send_age);
        /* The display engine reset under us. Re-run the bring-up to reset it
         * and re-arm the stream; the interface is preserved and repainted. */
        m_running = startPipeline();
    }
}

bool WuaDVI::temperature(int16_t *out_c10) const {
    if (out_c10 == nullptr)
        return false;
    uint32_t age_ms = 0;
    if (!display_link_get_rp_temp(out_c10, &age_ms))
        return false;
    return age_ms < WUADVI_RP_DEAD_MS;
}

uint32_t WuaDVI::rectsSent(void) const {
    return lvgl_port_rects_sent();
}

uint32_t WuaDVI::rectsFailed(void) const {
    return lvgl_port_rects_failed();
}

const char *WuaDVI::displayEngineVersion(void) {
    return RP_PAYLOAD_VERSION_STRING;
}
